packages:
  - packages/*
  - apps/*

catalog:
  '@number-flow/react': ^0.5.10
  '@orpc/client': ^1.9.0
  '@orpc/server': ^1.9.0
  '@playwright/test': ^1.55.1
  '@remixicon/react': ^4.6.0
  '@tanstack/react-query': ^5.90.2
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.132.7
  '@tanstack/react-router-devtools': ^1.132.7
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.3
  ai: ^5.0.53
  arktype: 2.1.20
  babel-plugin-react-compiler: 19.1.0-rc.2
  better-auth: ^1.3.17
  drizzle-kit: ^0.31.4
  drizzle-orm: 0.44.5
  motion: ^12.23.22
  nanoid: ^5.1.6
  react: ^19.1.1
  react-dom: ^19.1.1
  sonner: ^2.0.7
  tailwindcss: ^4.1.13
  tw-animate-css: ^1.4.0
  typescript: ^5.9.2
  uuid: ^13.0.0
  vite: ^7.1.7
  zod: ^4.1.11

onlyBuiltDependencies:
  - electron
